# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_SplashScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(651, 400)
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SME_Splashframe = QtWidgets.QFrame(self.centralwidget)
        self.SME_Splashframe.setStyleSheet("QFrame {    \n"
"   \n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0.0113636, stop:0 rgba(63, 105, 160, 255), stop:1 rgba(39, 81, 136, 255));\n"
"    border-radius: 10px;\n"
"}")
        self.SME_Splashframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SME_Splashframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SME_Splashframe.setObjectName("SME_Splashframe")
        self.progressBar = QtWidgets.QProgressBar(self.SME_Splashframe)
        self.progressBar.setGeometry(QtCore.QRect(40, 280, 561, 23))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    \n"
"    background-color: rgb(98, 114, 164);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0.0113636, stop:0 rgba(63, 105, 160, 255), stop:0.534091 rgba(45, 90, 198, 108), stop:0.994318 rgba(39, 81, 136, 255));\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_credits = QtWidgets.QLabel(self.SME_Splashframe)
        self.label_credits.setGeometry(QtCore.QRect(-10, 330, 651, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(213, 213, 213);\n"
"background-color: rgb(62, 104, 159);")
        self.label_credits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_credits.setObjectName("label_credits")
        self.label_loading = QtWidgets.QLabel(self.SME_Splashframe)
        self.label_loading.setGeometry(QtCore.QRect(-10, 250, 661, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("color: rgb(213, 213, 203);")
        self.label_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        self.label_description = QtWidgets.QLabel(self.SME_Splashframe)
        self.label_description.setGeometry(QtCore.QRect(-10, 190, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("color: rgb(98, 114, 164);")
        self.label_description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description.setObjectName("label_description")
        self.label = QtWidgets.QLabel(self.SME_Splashframe)
        self.label.setGeometry(QtCore.QRect(190, 60, 251, 111))
        self.label.setAutoFillBackground(True)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("SME-trans.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.SME_Splashframe)
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.label_credits.setText(_translate("SplashScreen", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Autor: Ismael Poblete V.</span></p></body></html>"))
        self.label_loading.setText(_translate("SplashScreen", "loading..."))
        self.label_description.setText(_translate("SplashScreen", "<html><head/><body><p><span style=\" font-weight:600; color:#d5d5d5;\">GUI GraphPlot: </span><span style=\" color:#d5d5d5;\">Simple Serial Graph Plot </span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SplashScreen = QtWidgets.QMainWindow()
    ui = Ui_SplashScreen()
    ui.setupUi(SplashScreen)
    SplashScreen.show()
    sys.exit(app.exec_())
